/* PFE — Auto-generated chart configurations */
/* Generated by generate_report.py — do not hand-edit */

function _initCharts() {
  /* Monte Carlo Fair Value Range */
  var el_ch_det_mc_range = document.getElementById('ch-det-mc-range');
  if (el_ch_det_mc_range) {
    new Chart(el_ch_det_mc_range, {
      type:'bar',
      data:{labels:["P5\u2013P25", "P25\u2013Median", "Median\u2013P75", "P75\u2013P95"],datasets:[{label:'Fair Value Range',data:[[-14.1, 1.68], [1.68, 16.3], [16.3, 41.52], [41.52, 124.88]],backgroundColor:[K.d7,K.d4,K.d2,K.d5],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+' \u2013 $'+r[1].toLocaleString();return c.dataset.label+': $'+r.toLocaleString()}}},annotation:{annotations:{ref0:{type:'line',yMin:26.58,yMax:26.58,borderColor:K.am,borderDash:[6,3],borderWidth:1.5,label:{display:true,content:'Current Price ($26.97)',position:'end',font:{size:10,weight:600},backgroundColor:'rgba(255,255,255,0.85)',color:K.am,padding:{left:6,right:6,top:2,bottom:2}}},ref1:{type:'line',yMin:16.3,yMax:16.3,borderColor:K.d1,borderWidth:1.5,label:{display:true,content:'Median ($16)',position:'end',font:{size:10,weight:600},backgroundColor:'rgba(255,255,255,0.85)',color:K.d1,padding:{left:6,right:6,top:2,bottom:2}}}}}},scales:{y:{grid:grd,ticks:{callback:function(v){return '$'+v.toLocaleString()}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.92,categoryPercentage:0.85}}}
    });
  }

  /* Valuation Multiples */
  var el_ch_det_multiples = document.getElementById('ch-det-multiples');
  if (el_ch_det_multiples) {
    new Chart(el_ch_det_multiples, {
      type:'line',
      data:{labels:["FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'P/E (trailing)',data:[4.9, 71.8, 18.9, 19.5],backgroundColor:K.d1,borderColor:K.d1,borderWidth:2}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>c.dataset.label+': '+c.raw+'x'}},annotation:{annotations:{ref0:{type:'line',yMin:28.8,yMax:28.8,borderColor:K.g2,borderDash:[6,3],borderWidth:1.5,label:{display:true,content:'Avg P/E (28.8x)',position:'end',font:{size:10,weight:600},backgroundColor:'rgba(255,255,255,0.85)',color:K.g2,padding:{left:6,right:6,top:2,bottom:2}}}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:v=>v+'x'}},x:{grid:ng}}}
    });
  }

  /* Revenue ($B) */
  var el_ch_revenue = document.getElementById('ch-revenue');
  if (el_ch_revenue) {
    new Chart(el_ch_revenue, {
      type:'bar',
      data:{labels:["FY2019", "FY2020", "FY2021", "FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'Revenue',data:[51.8, 41.9, 81.3, 101.2, 59.6, 63.6, 62.6],backgroundColor:[K.d8,K.d7,K.d6,K.d5,K.d4,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Net Income ($B) */
  var el_ch_net_income = document.getElementById('ch-net-income');
  if (el_ch_net_income) {
    new Chart(el_ch_net_income, {
      type:'bar',
      data:{labels:["FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'Net Income',data:[31.4, 2.1, 8.0, 7.8],backgroundColor:[K.d6,K.d4,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Net Income Trend */
  var el_ch_det_net_income = document.getElementById('ch-det-net-income');
  if (el_ch_det_net_income) {
    new Chart(el_ch_det_net_income, {
      type:'bar',
      data:{labels:["FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'Net Income ($B)',data:[31.37, 2.12, 8.03, 7.77],backgroundColor:[K.d6,K.d4,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Free Cash Flow Trend */
  var el_ch_det_fcf = document.getElementById('ch-det-fcf');
  if (el_ch_det_fcf) {
    new Chart(el_ch_det_fcf, {
      type:'bar',
      data:{labels:["FY2020", "FY2021", "FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'FCF ($B)',data:[12.18, 29.87, 26.03, 4.79, 9.84, 9.07],backgroundColor:[K.d8,K.d7,K.d5,K.d4,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Return on Equity Trend */
  var el_ch_det_roe = document.getElementById('ch-det-roe');
  if (el_ch_det_roe) {
    new Chart(el_ch_det_roe, {
      type:'bar',
      data:{labels:["FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'ROE (%)',data:[32.8, 2.4, 9.1, 9.0],backgroundColor:[K.d6,K.d4,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>c.dataset.label+': '+c.raw+'%'}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:v=>v+'%'}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Total Debt Trend */
  var el_ch_det_debt_trend_fin = document.getElementById('ch-det-debt-trend-fin');
  if (el_ch_det_debt_trend_fin) {
    new Chart(el_ch_det_debt_trend_fin, {
      type:'bar',
      data:{labels:["FY2015", "FY2016", "FY2020", "FY2021", "FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'Total Debt ($B)',data:[28.82, 31.4, 37.13, 36.2, 32.88, 61.54, 57.41, 61.64],backgroundColor:[K.d8,K.d7,K.d6,K.d5,K.d4,K.d3,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Payout Ratio Trend (Dividend + Buyback as % of FCF) */
  var el_ch_payout_pfe = document.getElementById('ch-payout-pfe');
  if (el_ch_payout_pfe) {
    new Chart(el_ch_payout_pfe, {
      type:'bar',
      data:{labels:["2021", "2022", "2023", "2024", "2025"],datasets:[{label:'Total Payout %',data:[45, 52, 58, 61, 65],backgroundColor:[K.d1,K.d1,K.d1,K.d1,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>c.dataset.label+': '+c.raw+'%'}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:v=>v+'%'}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Revenue Trend */
  var el_ch_det_revenue = document.getElementById('ch-det-revenue');
  if (el_ch_det_revenue) {
    new Chart(el_ch_det_revenue, {
      type:'bar',
      data:{labels:["FY2019", "FY2020", "FY2021", "FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'Revenue ($B)',data:[51.75, 41.91, 81.29, 101.17, 59.55, 63.63, 62.58],backgroundColor:[K.d8,K.d7,K.d6,K.d5,K.d4,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Global Pharma TAM Growth vs. PFE Revenue Trajectory */
  var el_ch_tam_001 = document.getElementById('ch-tam-001');
  if (el_ch_tam_001) {
    new Chart(el_ch_tam_001, {
      type:'bar',
      data:{labels:["2023", "2024", "2025", "2026E", "2027E", "2028E"],datasets:[{label:'Global Pharma TAM ($B)',data:[1480, 1540, 1600, 1665, 1730, 1800],backgroundColor:K.d1,borderSkipped:false},{label:'PFE Revenue ($B)',data:[58.5, 63.5, 62.58, 61.0, 63.5, 67.0],backgroundColor:K.d2,borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{usePointStyle:true,padding:12}},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* EPS Trend (Annual) */
  var el_ch_det_eps = document.getElementById('ch-det-eps');
  if (el_ch_det_eps) {
    new Chart(el_ch_det_eps, {
      type:'bar',
      data:{labels:["FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'EPS ($)',data:[5.47, 0.37, 1.41, 1.36],backgroundColor:[K.d6,K.d4,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+' \u2013 $'+r[1].toLocaleString();return c.dataset.label+': $'+r.toLocaleString()}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Factor Exposure Radar: PFE vs Universe Median */
  var el_ch_pfe_factor_001 = document.getElementById('ch-pfe-factor-001');
  if (el_ch_pfe_factor_001) {
    new Chart(el_ch_pfe_factor_001, {
      type:'bar',
      data:{labels:["Momentum", "Value", "Quality", "Size", "Volatility", "Growth"],datasets:[{label:'PFE Score',data:[42, 68, 55, 91, 73, 31],backgroundColor:'#2563eb',borderSkipped:false},{label:'Universe Median',data:[50, 50, 50, 50, 50, 50],backgroundColor:'#9ca3af',borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{usePointStyle:true,padding:12}}},scales:{y:{grid:grd,beginAtZero:true},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Total Debt Trend */
  var el_ch_det_debt_trend_risk = document.getElementById('ch-det-debt-trend-risk');
  if (el_ch_det_debt_trend_risk) {
    new Chart(el_ch_det_debt_trend_risk, {
      type:'bar',
      data:{labels:["FY2015", "FY2016", "FY2020", "FY2021", "FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'Total Debt ($B)',data:[28.82, 31.4, 37.13, 36.2, 32.88, 61.54, 57.41, 61.64],backgroundColor:[K.d8,K.d7,K.d6,K.d5,K.d4,K.d3,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',_initCharts)}else{_initCharts()}