/* PFE — Auto-generated D3 chart configurations */
/* Generated by generate_report.py — do not hand-edit */

function _initD3Charts() {
  if (typeof SS_D3 === 'undefined') return;

  /* Valuation Range by Method */
  SS_D3.renderFootballField('ch-d3-football-field', {"methods": [{"label": "DCF Base Case", "low": 50.95, "mid": 57.9, "high": 64.85}, {"label": "DCF Bull Case", "low": 122.65, "mid": 139.38, "high": 156.11}, {"label": "DCF Bear Case", "low": 23.4, "mid": 26.59, "high": 29.78}, {"label": "Monte Carlo Median", "low": 13.04, "mid": 16.3, "high": 19.56}, {"label": "Monte Carlo Mean", "low": 24.71, "mid": 30.89, "high": 37.07}, {"label": "Reverse DCF (Implied)", "low": 23.73, "mid": 26.97, "high": 30.21}], "current_price": 26.97, "height": "380px"});

  SS_D3.renderSparklines();

}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',_initD3Charts)}else{_initD3Charts()}