/* MELI — Auto-generated chart configurations */
/* Generated by generate_report.py — do not hand-edit */

function _initCharts() {
  /* Revenue ($B) */
  var el_ch_revenue = document.getElementById('ch-revenue');
  if (el_ch_revenue) {
    new Chart(el_ch_revenue, {
      type:'bar',
      data:{labels:["FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'Revenue',data:[10.5, 15.1, 20.8, 28.9],backgroundColor:[K.d6,K.d4,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Net Income ($B) */
  var el_ch_net_income = document.getElementById('ch-net-income');
  if (el_ch_net_income) {
    new Chart(el_ch_net_income, {
      type:'bar',
      data:{labels:["FY2023", "FY2024", "FY2025"],datasets:[{label:'Net Income',data:[1.0, 1.9, 2.0],backgroundColor:[K.d5,K.d3,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',_initCharts)}else{_initCharts()}