/* JPM — Auto-generated D3 chart configurations */
/* Generated by generate_report.py — do not hand-edit */

function _initD3Charts() {
  if (typeof SS_D3 === 'undefined') return;

  /* Valuation Range by Method */
  SS_D3.renderFootballField('ch-d3-football-field', {"methods": [{"label": "P/E Multiple (14x)", "low": 246.4, "mid": 280.0, "high": 313.6}, {"label": "P/B Multiple (2.0x)", "low": 235.84, "mid": 268.0, "high": 300.16}, {"label": "Gordon Growth Model", "low": 277.2, "mid": 315.0, "high": 352.8}, {"label": "Residual Income Model", "low": 268.4, "mid": 305.0, "high": 341.6}, {"label": "Reverse DCF (Market Implied)", "low": 249.04, "mid": 283.0, "high": 316.96}, {"label": "DCF (Standard FCF)", "low": 233.2, "mid": 265.0, "high": 296.8}], "current_price": 286.56, "height": "380px"});

  SS_D3.renderSparklines();

}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',_initD3Charts)}else{_initD3Charts()}