/* JPM — Auto-generated chart configurations */
/* Generated by generate_report.py — do not hand-edit */

function _initCharts() {
  /* Monte Carlo Fair Value Range */
  var el_ch_det_mc_range = document.getElementById('ch-det-mc-range');
  if (el_ch_det_mc_range) {
    new Chart(el_ch_det_mc_range, {
      type:'bar',
      data:{labels:["P5\u2013P25", "P25\u2013Median", "Median\u2013P75", "P75\u2013P95"],datasets:[{label:'Fair Value Range',data:[[-501.04, -286.24], [-286.24, -212.83], [-212.83, -170.76], [-170.76, -132.76]],backgroundColor:[K.d7,K.d4,K.d2,K.d5],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+' \u2013 $'+r[1].toLocaleString();return c.dataset.label+': $'+r.toLocaleString()}}},annotation:{annotations:{ref0:{type:'line',yMin:283.44,yMax:283.44,borderColor:K.am,borderDash:[6,3],borderWidth:1.5,label:{display:true,content:'Current Price ($286.56)',position:'end',font:{size:10,weight:600},backgroundColor:'rgba(255,255,255,0.85)',color:K.am,padding:{left:6,right:6,top:2,bottom:2}}},ref1:{type:'line',yMin:-212.83,yMax:-212.83,borderColor:K.d1,borderWidth:1.5,label:{display:true,content:'Median ($250)',position:'end',font:{size:10,weight:600},backgroundColor:'rgba(255,255,255,0.85)',color:K.d1,padding:{left:6,right:6,top:2,bottom:2}}}}}},scales:{y:{grid:grd,ticks:{callback:function(v){return '$'+v.toLocaleString()}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.92,categoryPercentage:0.85}}}
    });
  }

  /* Valuation Multiples */
  var el_ch_det_multiples = document.getElementById('ch-det-multiples');
  if (el_ch_det_multiples) {
    new Chart(el_ch_det_multiples, {
      type:'line',
      data:{labels:["FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'P/E (trailing)',data:[23.4, 17.5, 14.4, 14.2],backgroundColor:K.d1,borderColor:K.d1,borderWidth:2}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>c.dataset.label+': '+c.raw+'x'}},annotation:{annotations:{ref0:{type:'line',yMin:17.4,yMax:17.4,borderColor:K.g2,borderDash:[6,3],borderWidth:1.5,label:{display:true,content:'Avg P/E (17.4x)',position:'end',font:{size:10,weight:600},backgroundColor:'rgba(255,255,255,0.85)',color:K.g2,padding:{left:6,right:6,top:2,bottom:2}}}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:v=>v+'x'}},x:{grid:ng}}}
    });
  }

  /* Revenue ($B) */
  var el_ch_revenue = document.getElementById('ch-revenue');
  if (el_ch_revenue) {
    new Chart(el_ch_revenue, {
      type:'bar',
      data:{labels:["FY2018", "FY2019", "FY2020", "FY2021", "FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'Revenue',data:[109.0, 115.7, 120.0, 121.6, 128.7, 158.1, 177.6, 182.4],backgroundColor:[K.d8,K.d7,K.d6,K.d5,K.d4,K.d3,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Net Income ($B) */
  var el_ch_net_income = document.getElementById('ch-net-income');
  if (el_ch_net_income) {
    new Chart(el_ch_net_income, {
      type:'bar',
      data:{labels:["FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'Net Income',data:[37.7, 49.6, 58.5, 57.0],backgroundColor:[K.d6,K.d4,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Net Income Trend */
  var el_ch_det_net_income = document.getElementById('ch-det-net-income');
  if (el_ch_det_net_income) {
    new Chart(el_ch_det_net_income, {
      type:'bar',
      data:{labels:["FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'Net Income ($B)',data:[37.68, 49.55, 58.47, 57.05],backgroundColor:[K.d6,K.d4,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Return on Equity Trend */
  var el_ch_det_roe = document.getElementById('ch-det-roe');
  if (el_ch_det_roe) {
    new Chart(el_ch_det_roe, {
      type:'bar',
      data:{labels:["FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'ROE (%)',data:[12.9, 15.1, 17.0, 15.7],backgroundColor:[K.d6,K.d4,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>c.dataset.label+': '+c.raw+'%'}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:v=>v+'%'}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Total Debt Trend */
  var el_ch_det_debt_trend_fin = document.getElementById('ch-det-debt-trend-fin');
  if (el_ch_det_debt_trend_fin) {
    new Chart(el_ch_det_debt_trend_fin, {
      type:'bar',
      data:{labels:["FY2009", "FY2010", "FY2011", "FY2012", "FY2013"],datasets:[{label:'Total Debt ($B)',data:[266.32, 270.65, 256.77, 249.02, 267.89],backgroundColor:[K.d7,K.d5,K.d4,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Capital Return Trend (Buybacks + Dividends as % of Net Income) */
  var el_ch_capalloc_001 = document.getElementById('ch-capalloc-001');
  if (el_ch_capalloc_001) {
    new Chart(el_ch_capalloc_001, {
      type:'bar',
      data:{labels:["2021", "2022", "2023", "2024", "2025"],datasets:[{label:'Implied Payout Ratio %',data:[35, 40, 45, 48, 52],backgroundColor:[K.d7,K.d5,K.d4,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>c.dataset.label+': '+c.raw+'%'}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:v=>v+'%'}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Revenue Trend */
  var el_ch_det_revenue = document.getElementById('ch-det-revenue');
  if (el_ch_det_revenue) {
    new Chart(el_ch_det_revenue, {
      type:'bar',
      data:{labels:["FY2018", "FY2019", "FY2020", "FY2021", "FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'Revenue ($B)',data:[109.03, 115.72, 119.95, 121.65, 128.69, 158.1, 177.56, 182.45],backgroundColor:[K.d8,K.d7,K.d6,K.d5,K.d4,K.d3,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* TAM Growth Trajectory with JPM Revenue Overlay */
  var el_ch_tam_001 = document.getElementById('ch-tam-001');
  if (el_ch_tam_001) {
    new Chart(el_ch_tam_001, {
      type:'bar',
      data:{labels:["2023", "2024", "2025", "2026E", "2027E", "2028E"],datasets:[{label:'Total Addressable Market',data:[165.0, 172.5, 182.45, 195.0, 207.5, 220.4],backgroundColor:K.d1,borderSkipped:false},{label:'JPM Revenue',data:[158.1, 177.56, 182.45, 188.0, 196.5, 205.0],backgroundColor:'p1',borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{usePointStyle:true,padding:12}},tooltip:{callbacks:{label:c=>c.dataset.label+': '+c.raw+'%'}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:v=>v+'%'}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* EPS Trend (Annual) */
  var el_ch_det_eps = document.getElementById('ch-det-eps');
  if (el_ch_det_eps) {
    new Chart(el_ch_det_eps, {
      type:'bar',
      data:{labels:["FY2022", "FY2023", "FY2024", "FY2025"],datasets:[{label:'EPS ($)',data:[12.09, 16.23, 19.75, 20.02],backgroundColor:[K.d6,K.d4,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+' \u2013 $'+r[1].toLocaleString();return c.dataset.label+': $'+r.toLocaleString()}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Factor Exposure Radar Chart */
  var el_ch_jpm_factors = document.getElementById('ch-jpm-factors');
  if (el_ch_jpm_factors) {
    new Chart(el_ch_jpm_factors, {
      type:'bar',
      data:{labels:["Momentum", "Value", "Quality", "Size", "Volatility", "Growth"],datasets:[{label:'JPM Factor Scores',data:[68, 72, 81, 95, 54, 61],backgroundColor:'#1a73e8',borderSkipped:false},{label:'Universe Median',data:[50, 50, 50, 50, 50, 50],backgroundColor:'#9aa0a6',borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{usePointStyle:true,padding:12}}},scales:{y:{grid:grd,beginAtZero:true},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Total Debt Trend */
  var el_ch_det_debt_trend_risk = document.getElementById('ch-det-debt-trend-risk');
  if (el_ch_det_debt_trend_risk) {
    new Chart(el_ch_det_debt_trend_risk, {
      type:'bar',
      data:{labels:["FY2009", "FY2010", "FY2011", "FY2012", "FY2013"],datasets:[{label:'Total Debt ($B)',data:[266.32, 270.65, 256.77, 249.02, 267.89],backgroundColor:[K.d7,K.d5,K.d4,K.d2,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',_initCharts)}else{_initCharts()}