/* MSFT — Auto-generated chart configurations */
/* Generated by generate_report.py — do not hand-edit */

function _initCharts() {
  /* Revenue ($B) */
  var el_ch_revenue = document.getElementById('ch-revenue');
  if (el_ch_revenue) {
    new Chart(el_ch_revenue, {
      type:'bar',
      data:{labels:["FY2024", "FY2025"],datasets:[{label:'Revenue',data:[135.2, 158.9],backgroundColor:[K.d4,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Net Income ($B) */
  var el_ch_net_income = document.getElementById('ch-net-income');
  if (el_ch_net_income) {
    new Chart(el_ch_net_income, {
      type:'bar',
      data:{labels:["FY2024", "FY2025"],datasets:[{label:'Net Income',data:[240.0, 66.2],backgroundColor:[K.d4,K.d1],borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){var r=c.raw;if(Array.isArray(r))return c.dataset.label+': $'+r[0].toLocaleString()+'B'+' \u2013 $'+r[1].toLocaleString()+'B';return c.dataset.label+': $'+r.toLocaleString()+'B'}}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:function(v){return '$'+v.toLocaleString()+'B'}}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

  /* Implied vs. Modeled Growth Trajectory */
  var el_ch_tam_growth = document.getElementById('ch-tam-growth');
  if (el_ch_tam_growth) {
    new Chart(el_ch_tam_growth, {
      type:'bar',
      data:{labels:["Year 1", "Year 2", "Year 3", "Year 4", "Year 5", "Terminal"],datasets:[{label:'DCF Model Growth',data:[13.2, 11.2, 9.9, 8.9, 7.9, 2.5],backgroundColor:K.d1,borderSkipped:false},{label:'Market-Implied Growth',data:[59.7, 59.7, 59.7, 59.7, 59.7, 59.7],backgroundColor:K.d3,borderSkipped:false}]},
      options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{usePointStyle:true,padding:12}},tooltip:{callbacks:{label:c=>c.dataset.label+': '+c.raw+'%'}}},scales:{y:{grid:grd,beginAtZero:true,ticks:{callback:v=>v+'%'}},x:{grid:ng}},datasets:{bar:{barPercentage:0.7,categoryPercentage:0.8}}}
    });
  }

}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',_initCharts)}else{_initCharts()}