/* MSFT — Auto-generated D3 chart configurations */
/* Generated by generate_report.py — do not hand-edit */

function _initD3Charts() {
  if (typeof SS_D3 === 'undefined') return;

  /* Valuation Range by Method */
  SS_D3.renderFootballField('ch-d3-football-field', {"methods": [{"label": "DCF Base Case", "low": 272.8, "mid": 310.0, "high": 347.2}, {"label": "DCF Bull Case", "low": 334.4, "mid": 380.0, "high": 425.6}, {"label": "DCF Bear Case", "low": 211.2, "mid": 240.0, "high": 268.8}, {"label": "Monte Carlo Median", "low": 256.18, "mid": 320.23, "high": 384.28}, {"label": "Market-Implied Growth", "low": 336.05, "mid": 381.87, "high": 427.69}], "current_price": 381.87, "height": "380px"});

  SS_D3.renderSparklines();

}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',_initD3Charts)}else{_initD3Charts()}